### ISSUE TITLE
"문서에 메타 설명이 없습니다" 해결

### ISSUE THREAD

**Issue by ojj1123** [naro-Kim/snowy-window#8]
프로젝트가 정말 재미있네요 ^^ 잘보고 가용 ~~ 블로그보다가 아래 이슈 겪는거 같아 이슈 만들어봤어요

"문서에 메타 설명이 없습니다"를 해결하려면 아래 태그가 `head`에 들어가야 해요!
[lighthouse docs 참고](https://developer.chrome.com/docs/lighthouse/seo/meta-description?hl=ko)

```html
<meta name="description" content="Put your description here.">
```

지금 배포 된거 보니까 `name='desctiption'` 인 `meta` 태그가 없어서 lighthouse에서 `description`이 없다고 하는 것 같습니다. 코드 보니 `metadata`에 `description` 필드가 없네요. `og:description` 이랑은 달라요
https://github.com/naro-Kim/snowy-window/blob/1efd493aeab0b1dba745c8cefb1d533e13a12b33/src/app/layout.tsx#L8-L31

이렇게 수정하면 description meta 태그 들어갈거에요~ [Nextjs docs 참고](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#description)

```tsx
export const metadata: Metadata = {
  ...
  description: '설명 설명 설명',
  ...
}
```

그나저나 프로젝트 퀄리티 엄청나네요.. 👍 👍

**Comment by naro-Kim** [comment]
https://webmasters.stackexchange.com/questions/118056/whats-the-difference-between-og-description-and-meta-description

---
오.. og는 social media bot들을 위한 태그고 meta는 search engine을 위한 태그라 이런 차이가 났군요.. 분명하게 이해됐습니다~! 이슈에 솔루션까지 달아주셔서 감사해요 !  덕분에 SEO 처리까지 완료! 고마워요 상어맨~~

![image](https://github.com/naro-Kim/snowy-window/assets/51940808/f58af27d-1aef-498f-b238-f5a9a556bd84)
